version: "3.9"

services:
    app-web:
        container_name: ${HTTP_SERVER_NAME}
        build: .
        ports:
            - ${HTTP_SERVER_PORT}:8080
        depends_on:
            - db
        command: ./wait-db.sh db "./Land_data"
        environment:
            ENV: ${ENV}
            POSTGRES_USER: ${DB_USER_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}

    db:
        restart: always
        container_name: ${DB_NAME}
        image: postgis/postgis:16-3.4
        ports:
            - ${DB_PORT}:${DB_PORT}
        environment:
            POSTGRES_USER: ${DB_USER_NAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - ./.database/postgres/data:/var/lib/postgresql/data

    minio:
        image: minio/minio
        container_name: ${MINIO_NAME}
        restart: always
        command: server /data --console-address ":9002" --address ":9001"
        environment:
            MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
        ports:
            - ${MINIO_PORT}:${MINIO_PORT}
            - ${MINIO_WEB_PORT}:${MINIO_WEB_PORT}
        volumes:
            - minio-data:/data

volumes:
    minio-data:

